management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: e477a8005857fb55dd5eb955063f1497e9fba8d62212c2e0f6841b80f1735f6a
      expiration: 120000
      refresh-token:
         expiration: 604800000 # 7 days
            
